# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- feature/*

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/HFM.All.sln'
      setupSolution: '**/HFM.Setup.sln'
      entryProject: '**/HFM.csproj'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      targetFramework: 'net47'
      dotnetFive: 'net5.0'
      dotnetFiveWindows: 'net5.0-windows'

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '>= 5.5.1'

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: PowerShell@2
      displayName: 'HFM.Build - Update-AssemblyVersion'
      inputs:
        targetType: 'inline'
        script: |
          . .\HFM.Build.ps1
          Configure-Version -CommitCount
          Update-AssemblyVersion -AssemblyVersion $Global:Version -AssemblyFileVersion $Global:Version
          $buildNumber = "$env:BUILD_DEFINITIONNAME`_$Global:Version"
          Write-Host "##vso[build.updatebuildnumber]$buildNumber"
        workingDirectory: '.\src'

    - task: VSBuild@1
      displayName: 'Build - $(targetFramework)'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:TargetFramework=$(targetFramework) /p:NoWarn=1591'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      displayName: 'Test - $(targetFramework)'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*Tests.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        diagnosticsEnabled: true

    - task: PowerShell@2
      displayName: 'HFM.Build - Deploy-Build - $(targetFramework)'
      inputs:
        targetType: 'inline'
        script: |
          . .\HFM.Build.ps1
          Clean-Artifacts
          Deploy-Build -Verbose
        workingDirectory: '.\src'
        
    - task: PowerShell@2
      displayName: 'HFM.Build - Build-Zip - $(targetFramework)'
      inputs:
        targetType: 'inline'
        script: |
          . .\HFM.Build.ps1
          Configure-Version -CommitCount
          Build-Zip -Verbose
        workingDirectory: '.\src'

    - task: VSBuild@1
      displayName: 'Build Setup - $(targetFramework)'
      inputs:
        solution: $(setupSolution)
        platform: x86
        configuration: '$(buildConfiguration)'

    - task: PowerShell@2
      displayName: 'HFM.Build - Deploy-Msi - $(targetFramework)'
      inputs:
        targetType: 'inline'
        script: |
          . .\HFM.Build.ps1
          Configure-Version -CommitCount
          Deploy-Msi -Verbose
        workingDirectory: '.\src'
    
    - task: DotNetCoreCLI@2
      displayName: 'Restore - $(dotnetFiveWindows)'
      inputs:
        command: 'restore'
        projects: '$(solution)'
        
    - task: DotNetCoreCLI@2
      displayName: 'Build - $(dotnetFiveWindows)'
      inputs:
        command: 'build'
        projects: '$(entryProject)'
        arguments: '-f $(dotnetFiveWindows) -c $(buildConfiguration) --no-restore --verbosity normal'

    - task: DotNetCoreCLI@2
      displayName: 'Test HFM.Core - $(dotnetFive)'
      inputs:
        command: 'test'
        projects: '**/HFM.Core.Tests.csproj'
        arguments: '-f $(dotnetFive) -c $(buildConfiguration) --no-restore --verbosity normal --collect:"XPlat Code Coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Test HFM.Forms - $(dotnetFiveWindows)'
      inputs:
        command: 'test'
        projects: '**/HFM.Forms.Tests.csproj'
        arguments: '-f $(dotnetFiveWindows) -c $(buildConfiguration) --no-restore --verbosity normal --collect:"XPlat Code Coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Test HFM.Preferences - $(dotnetFive)'
      inputs:
        command: 'test'
        projects: '**/HFM.Preferences.Tests.csproj'
        arguments: '-f $(dotnetFive) -c $(buildConfiguration) --no-restore --verbosity normal --collect:"XPlat Code Coverage"'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage - $(dotnetFiveWindows)'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)\**\coverage.cobertura.xml'

    - task: DotNetCoreCLI@2
      displayName: 'Publish - $(dotnetFiveWindows)'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(entryProject)'
        arguments: '-f $(dotnetFiveWindows) -c $(buildConfiguration) --no-build --verbosity normal'
        zipAfterPublish: false
        modifyOutputPath: false

    - task: PowerShell@2
      displayName: 'HFM.Build - Deploy-Build - $(dotnetFiveWindows)'
      inputs:
        targetType: 'inline'
        script: |
          . .\HFM.Build.ps1
          Configure-TargetFramework -TargetFramework $(dotnetFiveWindows)
          Clean-Artifacts
          Deploy-Build -Verbose
        workingDirectory: '.\src'

    - task: PowerShell@2
      displayName: 'HFM.Build - Build-Zip - $(dotnetFiveWindows)'
      inputs:
        targetType: 'inline'
        script: |
          . .\HFM.Build.ps1
          Configure-TargetFramework -TargetFramework $(dotnetFiveWindows)
          Configure-Version -CommitCount
          Build-Zip -Verbose
        workingDirectory: '.\src'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          src\Artifacts\**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
