# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- feature/*

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/HFM.All.sln'
      setupSolution: '**/HFM.Setup.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: >= 5.5.1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - powershell: |
. .\HFM.Build.ps1
Configure-Version -CommitCount
Update-AssemblyVersion -Path 'ExeAssemblyVersion.cs' -AssemblyVersion $Global:Version -AssemblyFileVersion $Global:Version
Update-AssemblyVersion -Path 'AssemblyVersion.cs' -AssemblyVersion '1.0.0.0' -AssemblyFileVersion $Global:Version
      workingDirectory: '.\src'
      displayName: 'HFM.Build - Update-AssemblyVersion'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:NoWarn=1591'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*Tests.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        testFiltercriteria: 'Category!=Integration'
        codeCoverageEnabled: true
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        diagnosticsEnabled: true

    - powershell: |
. .\HFM.Build.ps1
Clean-Artifacts
Deploy-Build
      workingDirectory: '.\src'
      displayName: 'HFM.Build - Deploy-Build'

    - powershell: |
. .\HFM.Build.ps1
Configure-Version -CommitCount
Build-Zip
      workingDirectory: '.\src'
      displayName: 'HFM.Build - Build-Zip'

    - task: VSBuild@1
      inputs:
        solution: $(setupSolution)
        platform: x86
        configuration: '$(buildConfiguration)'

    - powershell: |
. .\HFM.Build.ps1
Configure-Version -CommitCount
Deploy-Msi
      workingDirectory: '.\src'
      displayName: 'HFM.Build - Deploy-Msi'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          src\GoogleDriveFunctions.ps1
          src\Artifacts\**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
